name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Determine base path
        shell: bash
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          # If repo/org variable BASE_PATH is defined, use it; otherwise auto-detect
          if [ -n "${{ vars.BASE_PATH }}" ]; then
            echo "NEXT_PUBLIC_BASE_PATH=${{ vars.BASE_PATH }}" >> "$GITHUB_ENV"
          elif [[ "$REPO_NAME" == *.github.io ]]; then
            # User/Org site -> root
            echo "NEXT_PUBLIC_BASE_PATH=" >> "$GITHUB_ENV"
          else
            # Project pages -> /<repo>
            echo "NEXT_PUBLIC_BASE_PATH=/$REPO_NAME" >> "$GITHUB_ENV"
          fi
          echo "Resolved NEXT_PUBLIC_BASE_PATH='$NEXT_PUBLIC_BASE_PATH'"

      - name: Build static site
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


